
import Head from "next/head";
import styled from "@emotion/styled";

export interface PageProps {
  children: React.ReactNode;
  title?: string;
  description?: string;
  noPad?: string;
}

const Wrapper = styled.div`
display: flex;
`

const Main = styled.main`
flex: 1 1 auto;
`

export const Page: React.FC<PageProps> = ({ title, description, noPad, children }) => {
  return (
    <Wrapper>
      <Head>
        {title && <title>{title}</title>}
        {description && <meta name="description" content="Generated by create next app" />}
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main style={{ padding: noPad ? '0' : '2em' }}>
        {children}
      </Main>
    </Wrapper>
  );
}

export default Page;

